### ISSUE TITLE
katana-extraapps cannot be installed because of conflicting files.

### ISSUE THREAD

**Issue by FredBezies** [fluxer/kde-extraapps#3]
Looks like PKGBUILD need to be tweaked. Building is OK, but installation is not.

Here is an error screenshot:

![VirtualBox_Arch - Katana_29_04_2019_01_34_58](https://user-images.githubusercontent.com/8571419/56871509-38bdbd00-6a1f-11e9-9d39-2f63bfd8e663.png)

Adding -DCMAKE_INSTALL_LIBDIR=/usr/lib in cmake could help, I think. Will test and report asap.

**Comment by FredBezies** [comment]
Modifying PKGBUILD worked.

**Comment by fluxer** [comment]
Thanks for reporting the issue and the fix!

**Comment by FredBezies** [comment]
You're welcome :)
